backend:
  name: github
  repo: adventphang/putra-heights-help
  branch: main
  base_url: https://astro-decap-cms-oauth-seven.vercel.app
  auth_endpoint: oauth

media_folder: "docs/assets"
public_folder: "/assets"

collections:
  - name: "pages"
    label: "Pages"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
